### ISSUE TITLE
应该可以打包成iOS或者Android的App吧?

### ISSUE THREAD

**Issue by chenchifeng** [klren0312/ironInfoWeapp#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by klren0312** [comment]
可以的 在hbuilderX里 [可以打包](https://uniapp.dcloud.io/quickstart?id=%E5%8F%91%E5%B8%83uni-app)
