### ISSUE TITLE
用户日志数据结构

### ISSUE THREAD

**Issue by yangangzhang** [klren0312/ironInfoWeapp#75]
您好，拜读了您的代码，在用户日志这块，log这张表中是不是关联对应的user_id？
![image](https://user-images.githubusercontent.com/20433039/80300432-5c9d1580-87cf-11ea-82f3-d78bf238509c.png)

**Comment by klren0312** [comment]
还没用上... 抱歉 后面加下

**Comment by klren0312** [comment]
> 您好，拜读了您的代码，在用户日志这块，log这张表中是不是关联对应的user_id？
> ![image](https://user-images.githubusercontent.com/20433039/80300432-5c9d1580-87cf-11ea-82f3-d78bf238509c.png)

已修改https://github.com/klren0312/ironInfoWeapp/commit/22bbfcdc7fd68e4038001499f63a8d86170d3ecb
